# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailspin < Formula
  desc "A better way to browse your logfiles"
  homepage "https://github.com/bensadeh/tailspin/"
  version "0.1"
  license "MIT"

  depends_on "less"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bensadeh/tailspin/releases/download/0.1/tailspin_0.1_macOS_arm64.tar.gz"
      sha256 "84a4663688ead27864d4140cf52d471a5d927812fb16d77eca019014da024f6e"

      def install
        bin.install "tailspin" => "spin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bensadeh/tailspin/releases/download/0.1/tailspin_0.1_macOS_64-bit.tar.gz"
      sha256 "d112259b3b39230d898fec02604f8ce61c6b9fcb7e65a02e936cb7f16256d69b"

      def install
        bin.install "tailspin" => "spin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bensadeh/tailspin/releases/download/0.1/tailspin_0.1_Linux_64-bit.tar.gz"
      sha256 "e0673166dc02e5a3ec15f892c52007837f4587ac59287d00f05a084d490c602c"

      def install
        bin.install "tailspin" => "spin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bensadeh/tailspin/releases/download/0.1/tailspin_0.1_Linux_arm64.tar.gz"
      sha256 "8c561153962681e9bffe4272c21477feecb06d87df1c3bf25b91addea060c944"

      def install
        bin.install "tailspin" => "spin"
      end
    end
  end
end
