# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailspin < Formula
  desc "A better way to browse your logfiles"
  homepage "https://github.com/bensadeh/tailspin/"
  version "0.1.1"
  license "MIT"

  depends_on "less"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bensadeh/tailspin/releases/download/0.1.1/tailspin_0.1.1_macOS_64-bit.tar.gz"
      sha256 "9f2fbcd9eabf99e36751df71113fddc6e981c40b30038c651ef6c214d7c7730e"

      def install
        bin.install "tailspin" => "spin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bensadeh/tailspin/releases/download/0.1.1/tailspin_0.1.1_macOS_arm64.tar.gz"
      sha256 "de44474cfa7e1e217194697eed751ba562e033dc5c16534769c8d882d7c21437"

      def install
        bin.install "tailspin" => "spin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bensadeh/tailspin/releases/download/0.1.1/tailspin_0.1.1_Linux_64-bit.tar.gz"
      sha256 "990c8170367be2901fc96b1d2866c8ce8db86558744614799038e3d7774972bf"

      def install
        bin.install "tailspin" => "spin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bensadeh/tailspin/releases/download/0.1.1/tailspin_0.1.1_Linux_arm64.tar.gz"
      sha256 "651202913e3039da068861f850a6a76824c65e6191910910cdb3e6c1fe8ca1fa"

      def install
        bin.install "tailspin" => "spin"
      end
    end
  end
end
